def generate_report(
    score,
    matched_skills,
    missing_skills,
    advice,
    gemini_feedback
):

    report = f"""
==========================================
AI RESUME SCREENING REPORT
==========================================

ATS SCORE
------------------------------------------
{score:.0f}%

MATCHED SKILLS
------------------------------------------
"""

    for skill in matched_skills:
        report += f"\n✓ {skill.title()}"

    report += "\n\nMISSING SKILLS\n"
    report += "------------------------------------------\n"

    for skill in missing_skills:
        report += f"\n✗ {skill.title()}"

    report += "\n\nCAREER ADVICE\n"
    report += "------------------------------------------\n"

    for item in advice:
        report += f"\n• {item}"

    report += "\n\nGEMINI AI ANALYSIS\n"
    report += "------------------------------------------\n"

    report += f"\n{gemini_feedback}"

    report += "\n\n=========================================="
    report += "\nGenerated by AI Resume Screening System"
    report += "\n=========================================="

    return report